extends RefCounted

func run(suite: RefCounted) -> void:
	var ball = load("res://scripts/ball/ball_controller.gd").new()
	ball.configure(load("res://scripts/config/prototype_tuning.gd").new())
	suite.expect_true(ball.has_method("apply_resting_interaction"), "V015 has scalar interaction separate from velocity")
	if not ball.has_method("apply_resting_interaction"):
		ball.free()
		return
	ball.configure_arena(Rect2(173, 133, 615, 448))
	ball.position = Vector2(480, 564.92)
	ball.vitality_model.set_vitality(0.04)
	load("res://tests/test_support.gd").prepare_resting(ball)
	ball.advance_resting_time(0.12)
	var visuals = load("res://scripts/ball/ball_visuals.gd").new()
	visuals.name = "Visuals"
	ball.add_child(visuals)
	ball.apply_resting_interaction(2.0, Vector2(650, 537))
	var first_deformation: Vector2 = visuals.deformation
	ball.apply_resting_interaction(3.0, Vector2(650, 537))
	suite.expect_true(first_deformation.y < 1.0, "first weak input produces visible response")
	suite.expect_true(visuals.deformation.y < first_deformation.y, "weak response increases continuously")
	suite.expect_equal(ball.velocity, Vector2.ZERO, "weak interaction never injects motion")
	suite.expect_float(ball.vitality_model.current_vitality, 0.04, 0.0001, "weak interaction preserves vitality")
	suite.expect_true(ball.is_resting(), "weak interaction keeps resting")
	suite.expect_false(ball.wake_consumed, "weak cannot consume strong eligibility")
	suite.expect_true(ball.apply_resting_interaction(8.0, Vector2(650, 537)), "weak then strong can activate")
	suite.expect_float(ball.velocity.y, -350, 0.001, "strong starts at fixed speed")
	suite.expect_float(ball.velocity.x, 0, 0.001, "no remote horizontal impulse")
	suite.expect_false(ball.apply_resting_interaction(80, Vector2(650, 537)), "one activation only")
	ball.start_active(Vector2.UP)
	ball.position = Vector2(480, 300)
	ball.vitality_model.set_vitality(0.04)
	load("res://tests/test_support.gd").prepare_resting(ball)
	ball.advance_air_motion(0.1)
	suite.expect_float(ball.velocity.y, 26, 0.001, "unsupported zero-velocity resting still falls")
	ball.free()
	# Overshoot strength, direction and airborne contact cannot stack launch energy.
	for distance in [12.5, 25.0, 100.0]:
		ball = load("res://scripts/ball/ball_controller.gd").new()
		ball.configure(load("res://scripts/config/prototype_tuning.gd").new())
		ball.configure_arena(Rect2(173, 133, 615, 448))
		ball.position = Vector2(480, 564.92)
		ball.vitality_model.set_vitality(0.04)
		load("res://tests/test_support.gd").prepare_resting(ball)
		suite.expect_false(ball.apply_resting_interaction(distance, Vector2(480, 537)), "rest delay rejects input")
		ball.advance_resting_time(0.12)
		suite.expect_false(ball.apply_resting_interaction(distance, Vector2(681, 537)), "range rejects input")
		suite.expect_true(ball.apply_resting_interaction(distance, Vector2(480, 537)), "threshold and overshoot activate")
		suite.expect_equal(ball.velocity, Vector2(0, -350), "launch is independent of input magnitude")
		suite.expect_float(ball.vitality_model.current_vitality, 0.34, 0.0001, "one fixed vitality recovery")
		ball.free()
	ball = load("res://scripts/ball/ball_controller.gd").new()
	ball.configure(load("res://scripts/config/prototype_tuning.gd").new())
	ball.vitality_model.set_vitality(0.04)
	load("res://tests/test_support.gd").prepare_resting(ball)
	ball.position = Vector2(480, 300)
	ball.velocity = Vector2(25, -200)
	ball.advance_resting_time(0.12)
	suite.expect_true(ball.apply_resting_interaction(25, Vector2(480, 537)), "airborne resting can regain activity")
	suite.expect_equal(ball.velocity, Vector2(25, -200), "existing airborne motion is not kicked again")
	ball.free()
	ball = load("res://scripts/ball/ball_controller.gd").new()
	var paddle := Node2D.new()
	paddle.position = Vector2(480, 537)
	ball.configure(load("res://scripts/config/prototype_tuning.gd").new())
	ball.configure_support(paddle)
	ball.position = Vector2(480, 511.92)
	ball.vitality_model.set_vitality(0.04)
	load("res://tests/test_support.gd").prepare_resting(ball)
	ball._refresh_support()
	ball.advance_resting_time(0.12)
	ball.apply_resting_interaction(10, paddle.position)
	paddle.position.x = 600
	suite.expect_false(ball.apply_resting_interaction(3, paddle.position), "support loss clears old strength before processing new input")
	ball.free()
	paddle.free()
