extends SceneTree
const Support = preload("res://tests/test_support.gd")
class Blocker extends Node:
	func entity_envelopes() -> Array[Rect2]: return [Rect2(0,0,960,720)]
var suite = Support.new()
func _init() -> void: call_deferred("_run")
func _run() -> void:
	var main = load("res://scenes/main.tscn").instantiate()
	root.add_child(main)
	for frame in range(5): await physics_frame
	suite.expect_not_null(main.get("bricks"),"third harvest default contains brick family")
	if main.get("bricks") != null: await _check(main)
	main.queue_free()
	await process_frame
	await process_frame
	var deadline := Time.get_ticks_msec()+300
	while Time.get_ticks_msec()<deadline: await process_frame
	suite.print_summary()
	quit(0 if suite.failures == 0 else 1)

func _check(main) -> void:
	var bricks = main.bricks
	var ball = main.ball
	for node in [bricks,main.play_world,main.portals,main.geometry_playground.toys,ball,main.paddle]: node.set_physics_process(false)
	main.geometry_playground.toys.set_layout(0)
	main.play_world._states = {"rotor":"absent","charge":"absent"}
	main.portals.phase = "absent"
	main.portals.mouths.clear()
	bricks.clear()
	var ordinary = bricks.add_brick("ordinary",Vector2(300,200),20.0)
	var reverse = bricks.add_brick("reverse",Vector2(680,200),20.0)
	ball.position = Vector2(300,170)
	ball.start_active(Vector2.DOWN)
	ball.velocity = Vector2(0,500)
	var vitality: float = ball.vitality_model.current_vitality
	ball.resolve_surface_collision(0,Vector2.UP,false,0,ordinary)
	suite.expect_equal(ordinary.get_meta("stage"),"cracked","ordinary first committed hit cracks")
	suite.expect_true(ball.vitality_model.current_vitality <= vitality,"brick adds no vitality")
	ball.velocity = Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,ordinary)
	suite.expect_equal(ordinary.get_meta("stage"),"cracked","same resident contact cannot consume second hit")
	ball.position = Vector2(480,100)
	bricks._physics_process(0.2)
	ball.position = Vector2(300,170)
	ball.velocity = Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,ordinary)
	suite.expect_equal(ordinary.get_meta("phase"),"shattering","second independent hit shatters")
	suite.expect_equal(ordinary.collision_layer,0,"shattered brick immediately stops collision")
	suite.expect_false(main.play_world._geometry_clear(Vector2(300,200),24),"shatter visible body retains occupancy")
	bricks._physics_process(0.66)
	suite.expect_equal(bricks.bodies.size(),1,"shattered body removed without regrowth")
	ball.position = Vector2(680,170)
	ball.velocity = Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	suite.expect_equal(reverse.get_meta("stage"),"assembling","reverse first hit begins assembly")
	suite.expect_equal(reverse.collision_layer,1,"assembly retains reliable collision")
	var remaining: float = reverse.get_meta("remaining")
	ball.position = Vector2(480,100)
	bricks._physics_process(0.1)
	ball.position = Vector2(680,170)
	ball.velocity = Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	suite.expect_equal(reverse.get_meta("stage"),"assembling","assembly contact cannot spend second hit")
	bricks._physics_process(0.2)
	suite.expect_equal(reverse.get_meta("stage"),"assembled","assembly completes after 0.28 seconds")
	suite.expect_true(reverse.get_meta("remaining") < remaining,"assembly never extends lifetime")
	ball.velocity = Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	suite.expect_equal(reverse.get_meta("stage"),"assembled","resident assembly contact must leave after completion")
	ball.position = Vector2(480,100)
	bricks._physics_process(0.2)
	ball.position = Vector2(680,170)
	ball.velocity = Vector2(0,780)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	suite.expect_equal(reverse.get_meta("phase"),"shattering","reverse independent second hit shatters")
	suite.expect_equal(bricks.events.back().kind,"toy_reverse_break","reverse final break has stronger dedicated event")
	bricks._physics_process(0.66)
	suite.expect_true(bricks.bodies.is_empty(),"reverse has no permanent result")
	# Real engine fast flight, not just calling the collision callback.
	ordinary = bricks.add_brick("ordinary",Vector2(480,200),20.0)
	ball.position = Vector2(480,140)
	ball.start_active(Vector2.DOWN)
	ball.velocity = Vector2(0,780)
	ball.set_physics_process(true)
	for frame in range(8): await physics_frame
	ball.set_physics_process(false)
	suite.expect_equal(ordinary.get_meta("stage"),"cracked","fast780 actual sweep hits the brick")
	bricks.clear()
	# Shared occupancy is bidirectional and includes every visible state.
	ordinary = bricks.add_brick("ordinary",Vector2(480,240),20.0)
	for phase in ["appearing","active","fading","shattering"]:
		ordinary.set_meta("phase",phase)
		suite.expect_false(main.play_world._geometry_clear(Vector2(480,240),24),"world avoids brick "+phase)
		suite.expect_false(main.geometry_playground.toys._legal_point("bumper",Vector2(480,240),Vector2.UP),"geometry avoids brick "+phase)
		suite.expect_false(main.portals.outlet_clear(Vector2(480,240),27,ball),"portal outlet avoids brick "+phase)
	bricks.clear()
	main.play_world._states.charge="fading"
	main.play_world.charge_position=Vector2(300,240)
	suite.expect_false(bricks._legal(Vector2(300,240)),"brick avoids Area2D charge fading")
	main.play_world._states.charge="absent"
	main.portals.phase="appearing"
	main.portals.mouths.assign([Vector2(300,240),Vector2(740,240)])
	suite.expect_false(bricks._legal(Vector2(300,240)),"brick avoids appearing portal")
	main.portals.phase="absent"
	main.portals.mouths.clear()
	main.geometry_playground.toys._add("seesaw",Vector2(400,300))
	suite.expect_false(bricks._legal(Vector2(465,333)),"brick avoids full seesaw motion envelope")
	main.geometry_playground.toys.set_layout(0)
	reverse=bricks.add_brick("reverse",Vector2(680,200),0.2)
	ball.position=Vector2(680,170)
	ball.start_active(Vector2.DOWN)
	ball.velocity=Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	bricks._physics_process(0.21)
	suite.expect_equal(reverse.get_meta("phase"),"fading","expiry during assembly never grants extra lifetime")
	bricks.clear()
	reverse=bricks.add_brick("reverse",Vector2(680,200),20.0)
	ball.velocity=Vector2(0,10)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	suite.expect_equal(reverse.get_meta("stage"),"scattered","low support contact is not a meaningful hit")
	ball.vitality_model.set_vitality(0)
	ball.vitality_model.resolve_activity(true)
	ball.velocity=Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	suite.expect_equal(reverse.get_meta("stage"),"scattered","RESTING never consumes brick state")
	ball.start_active(Vector2.DOWN)
	ball.velocity=Vector2(0,500)
	ball.resolve_surface_collision(0,Vector2.UP,false,0,reverse)
	bricks._physics_process(0.1)
	var saved_assembly: Dictionary=bricks.export_snapshot()
	suite.expect_true(main.geometry_playground.save_combination(),"save full composition during assembly")
	suite.expect_true(bricks.snapshot_valid(saved_assembly),"mid-assembly schema is valid")
	bricks._physics_process(0.1)
	suite.expect_true(main.geometry_playground.restore_combination(),"mid-assembly full composition restores exact progress")
	reverse=bricks.bodies[0]
	suite.expect_float(reverse.get_meta("assembly_time"),0.1,0.001,"saved assembly time not reset")
	suite.expect_float(reverse.get_meta("remaining"),19.9,0.001,"saved natural lifetime not reset")
	bricks._physics_process(0.17)
	suite.expect_equal(reverse.get_meta("stage"),"assembling","restored assembly honors remaining duration")
	bricks._physics_process(0.02)
	suite.expect_equal(reverse.get_meta("stage"),"assembled","restored assembly finishes after remaining duration")
	bricks.clear()
	var blocker:=Blocker.new()
	main.spawn_occupancy.register(blocker)
	suite.expect_false(bricks._try_spawn(),"occupied scene cannot force a brick spawn")
	suite.expect_true(bricks.bodies.is_empty(),"failed spawn leaves no brick body")
	main.spawn_occupancy.unregister(blocker)
	blocker.free()
	for x in [200,400,600]: bricks.add_brick("ordinary",Vector2(x,200),20)
	suite.expect_false(bricks._try_spawn(),"three-brick cap is finite")
	var duplicate_data: Dictionary=bricks.export_snapshot()
	duplicate_data.bodies[1].id=duplicate_data.bodies[0].id
	suite.expect_false(bricks.snapshot_valid(duplicate_data),"duplicate brick identity rejected by schema")
	bricks.clear()
	main.geometry_playground.restart_world(184)
	suite.expect_true(main.geometry_playground.save_combination(),"v4 combination saves")
	var path: String = main.geometry_playground.last_saved_path
	var data = JSON.parse_string(FileAccess.get_file_as_string(path))
	suite.expect_equal(data.version,4,"brick composition uses v4")
	suite.expect_equal(data.world_mode,"coexistence-bricks","v4 identifies cumulative brick mode")
	suite.expect_true(main.geometry_playground.restore_combination(path),"v4 restores matching mode")
	var before: String=JSON.stringify(bricks.export_snapshot())
	var bad_path: String="res://.godot/brick-harvest-20261001/invalid.json"
	data.version=3
	data.world_mode="coexistence-portals"
	data.erase("bricks")
	var file=FileAccess.open(bad_path,FileAccess.WRITE)
	file.store_string(JSON.stringify(data)); file.close()
	suite.expect_false(main.geometry_playground.restore_combination(bad_path),"v3 cannot silently become a brick composition")
	suite.expect_equal(JSON.stringify(bricks.export_snapshot()),before,"rejected old format leaves bricks unchanged")
	data=JSON.parse_string(FileAccess.get_file_as_string(path))
	ordinary=bricks.add_brick("ordinary",Vector2(300,240),20)
	data.bricks=bricks.export_snapshot()
	bricks.clear()
	data.world.states.charge="active"
	data.world.charge=[300,240]
	file=FileAccess.open(bad_path,FileAccess.WRITE)
	file.store_string(JSON.stringify(data)); file.close()
	before=JSON.stringify(bricks.export_snapshot())
	suite.expect_false(main.geometry_playground.restore_combination(bad_path),"v4 overlapping charge and brick reject before mutation")
	suite.expect_equal(JSON.stringify(bricks.export_snapshot()),before,"overlap rejection leaves brick timeline unchanged")
