extends SceneTree
const Tuning = preload("res://scripts/config/prototype_tuning.gd")
const Toys = preload("res://scripts/world/geometry_toys.gd")
const Result = preload("res://scripts/physics/surface_collision_result.gd")
const Visuals = preload("res://scripts/ball/ball_visuals.gd")
const Support = preload("res://tests/test_support.gd")
func _init() -> void: call_deferred("_run")
func _run() -> void:
	var suite = Support.new()
	var tuning = Tuning.new()
	suite.expect_true(tuning.has_method("apply_motion_profile"), "profile can be explicitly initialized")
	if tuning.has_method("apply_motion_profile"):
		tuning.apply_motion_profile("fast")
		suite.expect_float(tuning.initial_speed, 540, 0.001, "fast initial speed")
		suite.expect_float(tuning.max_speed, 780, 0.001, "fast cap")
		suite.expect_float(tuning.gravity_acceleration, 585, 0.001, "fast gravity")
		suite.expect_float(tuning.continue_launch_speed, 435, 0.001, "fast Continue")
		suite.expect_float(tuning.spring_release_speed, 750, 0.001, "fast spring")
		suite.expect_float(tuning.wake_launch_speed, 525, 0.001, "fast Wake")
		suite.expect_float(tuning.paddle_impulse, 240, 0.001, "fast paddle impulse")
		suite.expect_float(tuning.bumper_normal_speed, 570, 0.001, "fast bumper normal speed")
		suite.expect_float(tuning.sling_normal_speed, 660, 0.001, "fast sling normal speed")
		suite.expect_float(tuning.rest_settle_speed, 67.5, 0.001, "physical rest threshold scales")
		suite.expect_float(tuning.spring_capture_speed, 52.5, 0.001, "spring speed eligibility scales")
		suite.expect_float(tuning.trail_reference_speed, 780, 0.001, "trail reference scales explicitly")
		var visuals = Visuals.new()
		visuals.configure(tuning)
		visuals.set_motion(Vector2(520, 0))
		var reference_ratio: float = visuals._speed_ratio()
		tuning.max_speed = 800
		suite.expect_float(visuals._speed_ratio(), reference_ratio, 0.00001, "F1 cap edit does not change trail scale")
		visuals.free()
		tuning.apply_motion_profile("fast")
		suite.expect_float(tuning.initial_speed, 540, 0.001, "reapplying does not compound")
		tuning.apply_motion_profile("current")
		suite.expect_float(tuning.initial_speed, 360, 0.001, "current restored exactly")
		suite.expect_float(tuning.continue_launch_speed, 290, 0.001, "current Continue")
		suite.expect_float(tuning.spring_release_speed, 500, 0.001, "current spring")
	var toys = Toys.new()
	root.add_child(toys)
	toys.set_physics_process(false)
	toys.configure(Rect2(0, 0, 960, 720))
	toys.set_layout(1)
	var result = Result.new()
	result.velocity_before = Vector2(600, 300)
	result.normal = Vector2.UP
	var collider: StaticBody2D = toys.get_children()[2]
	var request: Dictionary = toys.contact_request(result, collider, Vector2.ZERO)
	suite.expect_true(request.velocity.length() > 520, "geometry returns unbounded physical response")
	toys.free()
	suite.print_summary()
	quit(0 if suite.failures == 0 else 1)
