extends RefCounted

const Ball = preload("res://scripts/ball/ball_controller.gd")
const Visuals = preload("res://scripts/ball/ball_visuals.gd")
const Paddle = preload("res://scripts/paddle/paddle_controller.gd")
const Audio = preload("res://scripts/audio/basic_audio_feedback.gd")
const Surface = preload("res://scripts/physics/surface_response_model.gd")
const Tuning = preload("res://scripts/config/prototype_tuning.gd")

func run(suite: RefCounted) -> void:
	var tuning: Resource = Tuning.new()
	var paddle: CharacterBody2D = Paddle.new()
	paddle.configure(tuning, 175, 786, 570)
	var ball: CharacterBody2D = Ball.new()
	var visuals: Node2D = Visuals.new()
	visuals.name = "Visuals"
	ball.add_child(visuals)
	ball.configure(tuning)
	var events: Array[RefCounted] = []
	ball.surface_resolved.connect(func(result: RefCounted): events.append(result))
	paddle.set_target_x(510)
	paddle.advance_motion(1.0 / 60.0)
	for speed in [60.0, 220.0, 900.0]:
		paddle.advance_feedback(1.0)
		visuals.advance_feedback(1.0)
		ball.vitality_model.set_vitality(1.0)
		ball.velocity = Vector2(900, speed)
		ball.resolve_surface_collision(Surface.SurfaceKind.PADDLE, Vector2.UP, true)
		suite.expect_true(visuals.deformation.y < 1.0, "real top impact compresses Ball")
	paddle.advance_feedback(1.0)
	visuals.advance_feedback(1.0)
	ball.vitality_model.set_vitality(0.05)
	ball.velocity = Vector2(0, 180)
	ball.resolve_surface_collision(Surface.SurfaceKind.PADDLE, Vector2.UP, true)
	paddle.advance_feedback(1.0)
	suite.expect_equal(events.size(), 4, "four resolved top contacts emitted")
	var audio: Node = Audio.new()
	audio.initialize()
	audio.on_surface_resolved(events[0])
	var weak_volume: float = audio.players[0].volume_db
	var weak_pitch: float = audio.players[0].pitch_scale
	audio.advance_time(0.2)
	audio.on_surface_resolved(events[2])
	suite.expect_true(audio.players[0].volume_db > weak_volume and audio.players[0].pitch_scale > weak_pitch, "strong normal hit sounds distinct from weak")
	audio.advance_time(0.2)
	audio.request_sound(audio.Event.GROUND)
	var ground_volume: float = audio.players[audio.Event.GROUND].volume_db
	audio.advance_time(0.02)
	suite.expect_true(audio.request_sound(audio.Event.PADDLE), "Paddle wins within 40 ms of Ground")
	suite.expect_true(audio.players[audio.Event.GROUND].volume_db < ground_volume, "prior Ground voice yields to Paddle without a hard stop")
	suite.expect_false(audio.request_sound(audio.Event.PADDLE), "priority does not bypass Paddle cooldown")
	suite.expect_float(audio.players[audio.Event.GROUND].volume_db, ground_volume - 8.0, 0.0001, "priority ducks Ground once by a bounded amount")
	audio.advance_time(0.2)
	suite.expect_true(audio.request_sound(audio.Event.GROUND), "later Ground may sound independently")
	suite.expect_float(audio.players[audio.Event.GROUND].volume_db, ground_volume, 0.0001, "new Ground voice restores its base level")
	audio.advance_time(0.02)
	suite.expect_true(audio.request_sound(audio.Event.PADDLE), "later Ground to Paddle pair remains eligible")
	suite.expect_float(audio.players[audio.Event.GROUND].volume_db, ground_volume - 8.0, 0.0001, "repeated priority does not accumulate ducking")
	audio.free()
	ball.free()
	paddle.free()
