extends RefCounted

const Visuals = preload("res://scripts/ball/ball_visuals.gd")
const Paddle = preload("res://scripts/paddle/paddle_controller.gd")
const Tuning = preload("res://scripts/config/prototype_tuning.gd")
const Vitality = preload("res://scripts/ball/ball_vitality_model.gd")
const Response = preload("res://scripts/physics/surface_response_model.gd")


func run(suite: RefCounted) -> void:
	var visuals: Node2D = Visuals.new()
	visuals.configure(Tuning.new())
	suite.expect_true(visuals.has_method("glow_peak"), "frozen visuals expose Vitality glow")
	suite.expect_true(visuals.has_method("advance_motion_history"), "Trail samples elapsed motion time")
	if not visuals.has_method("glow_peak") or not visuals.has_method("advance_motion_history"):
		visuals.free()
		return
	visuals.set_vitality(1.0, Vitality.ActivityState.ACTIVE)
	visuals.set_motion(Vector2(520, 0))
	suite.expect_equal(visuals.core_color().to_html(false), "e6fbff", "full Vitality uses near-white center-color Core")
	suite.expect_float(visuals.glow_peak(), 0.80, 0.0001, "full Vitality Glow peak")
	suite.expect_float(visuals.glow_envelope(), 1.95, 0.0001, "full Vitality Glow envelope")
	var peak: float = visuals.glow_peak()
	var color: Color = visuals.core_color()
	visuals.set_motion(Vector2(130, 0))
	suite.expect_float(visuals.glow_peak(), peak, 0.0001, "Velocity cannot change Glow intensity")
	suite.expect_equal(visuals.core_color(), color, "Velocity cannot change Core color")
	visuals.play_collision_feedback(Response.SurfaceKind.PADDLE, Vector2.UP)
	suite.expect_float(visuals.glow_peak(), peak, 0.0001, "collision decoration cannot boost Glow")
	visuals.play_wake_feedback()
	suite.expect_float(visuals.glow_peak(), peak, 0.0001, "Wake decoration cannot boost Glow")
	suite.expect_true(visuals.deformation.x < 1.0, "Wake retains optional geometric feedback")
	visuals.set_vitality(0.4, Vitality.ActivityState.DECAYING)
	suite.expect_float(visuals.glow_peak(), 0.428, 0.0001, "Glow brightness continuously maps Vitality")
	suite.expect_float(visuals.glow_envelope(), 1.452, 0.0001, "Glow envelope continuously maps Vitality")
	suite.expect_equal(visuals.core_color().to_html(false), "bcdee3", "mid Vitality Core stays high contrast")
	suite.expect_equal(visuals.glow_color().to_html(false), "0ddbff", "Glow hue does not carry Vitality")
	visuals.set_vitality(0.04, Vitality.ActivityState.RESTING)
	var rest_color: Color = visuals.core_color()
	suite.expect_float(visuals.glow_peak(), 0.18, 0.0001, "RESTING has constant Glow floor")
	suite.expect_equal(rest_color.to_html(false), "a3cad1", "RESTING Core remains bright")
	visuals.set_vitality(0.0, Vitality.ActivityState.RESTING)
	suite.expect_float(visuals.glow_peak(), 0.18, 0.0001, "zero Vitality cannot extinguish RESTING Glow")
	suite.expect_equal(visuals.core_color(), rest_color, "RESTING Core remains legible at zero Vitality")
	suite.expect_float(visuals.glow_alpha_at_radius(1.12), 0.0, 0.00001, "RESTING Glow ends at 1.12 radii")
	suite.expect_float(visuals.glow_alpha_at_radius(1.0), 0.18, 0.00001, "Glow peaks at circle edge")
	suite.expect_true(visuals.glow_alpha_at_radius(1.04) > visuals.glow_alpha_at_radius(1.08),
		"Glow decreases continuously outside Core")
	visuals.set_motion(Vector2.ZERO)
	visuals.play_weak_feedback(0.2)
	var weak_shape: Vector2 = visuals.deformation
	visuals.play_weak_feedback(0.8)
	suite.expect_true(visuals.deformation.y < weak_shape.y, "stronger weak input gives larger geometric response")
	suite.expect_equal(visuals.core_color(), rest_color, "weak interaction does not change vitality color")
	suite.expect_float(visuals.glow_peak(), 0.18, 0.0001, "weak interaction does not pulse Glow")
	suite.expect_true(visuals.trail_ghosts().is_empty(), "stationary weak response creates no trail")
	visuals.advance_feedback(2.0)
	suite.expect_float(visuals.deformation.y, 1.0, 0.0001, "weak response relaxes after input stops")
	for frame_rate in [30, 60, 120]:
		visuals.clear_motion_history()
		visuals.set_motion(Vector2(520, 0))
		visuals.advance_motion_history(Vector2.ZERO, 0.0)
		for frame in range(frame_rate):
			visuals.advance_motion_history(Vector2(520.0 * (frame + 1) / frame_rate, 0), 1.0 / frame_rate)
		suite.expect_equal(visuals.trail_points.size(), 11, "fixed-time samples are frame-rate independent")
		suite.expect_equal(visuals.trail_ghosts().size(), 4, "fast motion displays four discrete ghosts")
		var ghosts: Array = visuals.trail_ghosts()
		suite.expect_float(ghosts[0].x, 520.0 - 44.2, 0.02, "ghost spacing encodes actual speed")
	var fast_ghosts: Array = visuals.trail_ghosts()
	var trail_color: Color = visuals.trail_color()
	visuals.set_vitality(1.0, Vitality.ActivityState.ACTIVE)
	suite.expect_equal(visuals.trail_ghosts(), fast_ghosts, "Vitality cannot change ghost positions")
	suite.expect_equal(visuals.trail_color(), trail_color, "Trail always uses full Vitality Glow color")
	visuals.set_motion(Vector2(160, 0))
	suite.expect_equal(visuals.trail_ghosts().size(), 1, "160 px/s displays one ghost")
	suite.expect_float(visuals.trail_spacing(), 18.0, 0.001, "slow Trail maintains 18 px minimum spacing")
	visuals.set_motion(Vector2.ZERO)
	suite.expect_equal(visuals.trail_points.size(), 0, "stopping clears stale motion history")
	suite.expect_equal(visuals.trail_ghosts().size(), 0, "zero Velocity displays no Trail")
	visuals.free()
	_test_paddle_feedback(suite)


func _test_paddle_feedback(suite: RefCounted) -> void:
	var paddle: CharacterBody2D = Paddle.new()
	paddle.configure(Tuning.new(), 175, 786, 537)
	suite.expect_false(paddle.has_method("play_collision_feedback"), "contact alone draws nothing on the Paddle")
	suite.expect_equal(paddle.feedback_color().to_html(false), "80a2a8", "Paddle idle uses the Ball's center hue")
	paddle.play_energy_transfer(0.2)
	suite.expect_float(paddle.dim_strength(), 1.0, 0.0001, "large transfer dims fully")
	suite.expect_equal(paddle.feedback_color().to_html(false), "36494c", "dimmed body reaches the dim token")
	paddle.advance_feedback(0.08)
	suite.expect_float(paddle.dim_strength(), 1.0, 0.0001, "dim holds briefly so it can be seen")
	paddle.advance_feedback(0.25)
	suite.expect_true(paddle.dim_strength() > 0.2 and paddle.dim_strength() < 0.3, "recovery eases back")
	paddle.advance_feedback(1.0)
	suite.expect_float(paddle.dim_strength(), 0.0, 0.00001, "dim fully recovers")
	suite.expect_equal(paddle.feedback_color().to_html(false), "80a2a8", "Paddle returns exactly to idle")
	paddle.play_energy_transfer(0.01)
	suite.expect_true(paddle.dim_strength() >= 0.55, "any real transfer is clearly visible")
	var small: float = paddle.dim_strength()
	paddle.advance_feedback(1.0)
	paddle.play_energy_transfer(0.1)
	suite.expect_true(paddle.dim_strength() > small, "larger transfer dims deeper")
	paddle.advance_feedback(1.0)
	paddle.play_energy_transfer(0.0)
	suite.expect_float(paddle.dim_strength(), 0.0, 0.0001, "no transfer, no dim")
	paddle.free()
